name: Build and deploy action
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Копируем код из репозитория в runner
      - name: clone code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: docker Build
        uses: docker/build-push-action@v2
        #run: docker build -t my-image .
        run: docker build -t snz2010/hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker push
        run: docker push snz2010/hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID