name: Build and deploy action
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Копируем код из репозитория в runner
      - name: Clone Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Build
        run: docker build -t snz2010/hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: Docker Push
        run: docker push snz2010/hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy - Clone Code
        uses: actions/checkout@v3
      - name: Deploy - Render Configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
        #  cat config-ci.py | envsubst > deploy/config.py
      - name: Deploy - Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          # ssh - секреты с проекта гитхаба для доступа к ВМ
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # какие файлы копируем
          source: "deploy/docker-compose.yaml" #,deploy/config.py"
          # куда копируем
          target: "flask_app_ci"
          strip_components: 1
      - name: RUN APPLICATION
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd flask_app_ci
            echo ${{ secrets.PASSWORD }} | sudo -S $docker-compose up -d